name: GitHub Actions Demo
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Create env file
        run: |
          touch .gitignore
          echo **/.env >> .env
          cat .gitignore
      - run: echo "ğŸ This job's status is ${{ job.status }}."
